Предложения
## Получить список предложений
GET http://localhost:5000/offers HTTP/1.1
Content-Type: application/json

###
## Добавить новое предложение
POST http://localhost:5000/offers HTTP/1.1
Content-Type: application/json

{
  "title": "Уютная квартира в центре города",
  "description": "Современный дизайн и все удобства для комфортного проживания",
  "postDate": "2025-01-01T12:00:00.000Z",
  "city": "Dusseldorf",
  "previewImage": "apartment.jpg",
  "images": ["apartment1.jpg", "apartment2.jpg", "apartment3.jpg", "apartment4.jpg", "apartment5.jpg", "apartment6.jpg"],
  "isPremium": false,
  "rating": 0,
  "type": "apartment",
  "bedrooms": 3,
  "maxAdults": 5,
  "price": 1200,
  "goods": ["Breakfast", "Air conditioning", "Laptop friendly workspace", "Fridge"],
  "userId": "67d55eb0dcd1348e31280355",
  "commentsCount": 0,
  "location": { "latitude": "52.520008", "longitude": "13.404954" }
}

###

## Получить объявление по идентификатору
GET http://localhost:5000/offers/67e7eec380d5f0a01c3849a8 HTTP/1.1


###

## Удалить объявление по идентификатору
DELETE http://localhost:5000/offers/67e83bf5d0bf212d4af0906d HTTP/1.1

###

## Обновить объявление

PATCH http://localhost:5000/offers/67e837386c356275c7069e25 HTTP/1.1
Content-Type: application/json

{
  "title": "Ночной дозор 3",
  "description": "Проверка обновления обновления",
  "price": 1100
}

###
## Список комментариев к объявлению
GET http://localhost:5000/offers/67e83bf5d0bf212d4af0906d/comments HTTP/1.1

###
## Список премиальных предложений по городу
GET http://localhost:5000/offers/premium?city=Hamburg HTTP/1.1
