Предложения
## Получить список предложений
GET http://localhost:5000/offers HTTP/1.1
Content-Type: application/json

###
## Добавить новое предложение
POST http://localhost:5000/offers HTTP/1.1
Content-Type: application/json

{
  "title": "Новый отель 2.0",
  "description": "Отличное соотношение цена-качество",
  "city": "Hamburg",
  "previewImage": "home.jpg",
  "images": ["home1.jpg", "home2.jpg", "home3.jpg", "home4.jpg", "home5.jpg", "home6.jpg"],
  "isPremium": "true",
  "rating": "0",
  "type": "hotel",
  "bedrooms": "6",
  "maxAdults": "4",
  "price": "1000",
  "goods": ["Washer", "Fridge"],
  "userId": "67e6ede9445b8f44306cc317",
  "commentsCount": "0",
  "location": { "latitude": "48.85661", "longitude": "2.351499" }
}

###
